columns:
  - distance: int
  - cab_type: category
  - destination: category
  - source: category
  - price: float
  - surge_multiplier: int
  - name: category
  - Period_Of_Time: category


numerical_columns:
  - distance
  - price
  - surge_multiplier

categorical_columns:
  - cab_type
  - destination
  - source
  - name
  - Period_Of_Time