columns:
  - product_id: int
  - Product_Name: category
  - Category_ID: int
  - Launch_Date: datetime
  - sale_id: int
  - sale_date: datetime
  - store_id: int
  - quantity: int
  - Store_Name: category
  - City: category
  - category_name: category
  - Total_Sales: float
  - sale_year : int
  - sale_month : int
  - Lauch_Year : int
  - Launch_Month : int


numerical_columns:
  - product_id
  - Category_ID
  - sale_id
  - store_id
  - quantity
  - Total_Sales
  - sale_year
  - sale_month
  - Launch_Year
  - Launch_Month

categorical_columns:
  - Product_Name
  - category_name

datetime_columns:
  - Launch_Date
  - sale_date
drop_columns:
  - product_id
  - Category_ID
  - Launch_Date
  - sale_date
  - store_id

num_features:
  - 

mm_columns:
  - quantity
